# GFE Google Cloud Run Dockerfile

# Use the official Python image as base
FROM python:3.10-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set working directory
WORKDIR /app

# Copy project files
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Port Cloud Run listens on
ENV PORT 8080

# Start the server
CMD ["gunicorn", "--bind", ":8080", "main:app"]
